# Generated by Django 4.2.6 on 2024-08-31 08:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("signupuser", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Student",
        ),
    ]
